### ISSUE TITLE
Failing test case axiom.test.test_xatop.ProcessConcurrencyTestCase.testNewItemTypeInSubprocess

### ISSUE THREAD

**Issue by divmod-migration** [twisted/axiom#21]
I have no idea what this means, but this test case fails on trunk for me.

Axiom ❯ trial axiom.test.test_xatop.ProcessConcurrencyTestCase.testNewItemTypeInSubprocess                                                                                                                ⏎
axiom.test.test_xatop
  ProcessConcurrencyTestCase
    testNewItemTypeInSubprocess ...                                     [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: twisted.internet.error.ProcessDone: A process has ended without apparent errors: process finished with exit code 0.

axiom.test.test_xatop.ProcessConcurrencyTestCase.testNewItemTypeInSubprocess
-------------------------------------------------------------------------------
Ran 1 tests in 0.249s

FAILED (errors=1)

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-08-05T10:39:15Z
 * owner: lvh
 * the launchpad url was https://bugs.launchpad.net/bugs/1208426

**Comment by mithrandi** [comment]
This isn't currently failing, the failure was possibly caused by environment issues with the subprocess ending up with the wrong `sys.path`.
