### ISSUE TITLE
Benchmark for item batch deletion

### ISSUE THREAD

**Issue by divmod-migration** [twisted/axiom#4]
There should be a benchmark for item deletion.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-08-05T02:58:37Z
 * owner: mithrandi
 * assignee: mithrandi
 * the launchpad url was https://bugs.launchpad.net/bugs/1208298

**Comment by mithrandi** [comment]
This was fixed, but the bug never marked closed.
