### ISSUE TITLE
Deprecate startswith/endswith on bytes columns

### ISSUE THREAD

**Issue by mithrandi** [twisted/axiom#56]
These are implemented using the LIKE operator, which does not work on BLOB values when SQLite 3 is compiled with the SQLITE_LIKE_DOESNT_MATCH_BLOBS option (which Debian is now doing). The [SQLite documentation](https://www.sqlite.org/compile.html) has this to say:

> SQLITE_LIKE_DOESNT_MATCH_BLOBS
> 
> This compile-time option causes the LIKE operator to always return False if either operand is a BLOB. The default behavior of LIKE is that BLOB operands are cast to TEXT before the comparison is done.
> 
> This compile-time option makes SQLite run more efficiently when processing queries that use the LIKE operator, at the expense of breaking backwards compatibility. However, the backwards compatibility break may be only a technicality. There was a long-standing bug in the LIKE processing logic (see https://www.sqlite.org/src/info/05f43be8fdda9f) that caused it to misbehavior for BLOB operands and nobody observed that bug in nearly 10 years of active use. So for more users, it is probably safe to enable this compile-time option and thereby save a little CPU time on LIKE queries.

Thus I would suggest deprecating this functionality and removing any reliance on it from the test suite; this would allow any users with a suitably-compiled SQLite 3 to continue using the functionality for the time being.

**Comment by glyph** [comment]
This sounds good to me. Slightly unfortunate to lose this functionality (but that's really Debian's fault, here), but `bytes` values in the database are really intended to be opaque blobs, not the sort of things you should be executing queries against anyway.
