### ISSUE TITLE
axiomatic start special argument handling supports "--opt value" but does not support "--opt=value"

### ISSUE THREAD

**Issue by ldanielburr** [twisted/axiom#57]
Example (twisted 15.5.0, axiom 0.7.4):

    axiomatic --dbdir=my.axiom start --nodaemon --reactor=epoll

Some brief investigation reveals that axiom/scheduler.py is at least one place where the reactor is imported at module-import-time.  Moving that import into the _SiteScheduler class allows the --reactor flag to be processed successfully.

**Comment by mithrandi** [comment]
Does `axiomatic --dbdir my.axiom start --nodaemon --reactor epoll` work for you? There's unfortunately a bunch of code in the `axiomatic start` path that tries to detect certain options that need to be handled specially, but the code is written in such a way that it only works with the `--opt value` style, not `--opt=value`, even though `twisted.python.usage` supports both.

**Comment by ldanielburr** [comment]
@mithrandi - Invoking axiomatic in the manner you suggested appears to work, thank you.

As an side, this behavior totally blows my mind; is it worth a patch, do you think?

**Comment by mithrandi** [comment]
It's very confusing to run into (as you just inadvertently demonstrated), so I definitely think it's worth fixing. I *think* all of the code that does this is isolated to `axiom.scripts.axiomatic.Start`. (It's basically all stuff like `if "--reactor" in args`, where `args` is a list)

**Comment by ldanielburr** [comment]
@mithrandi - If you don't mind, I'll work up a pull-request for this.

**Comment by mithrandi** [comment]
Go for it :)

**Comment by ldanielburr** [comment]
Pull request #59 submitted.
