### ISSUE TITLE
Decorator for installables

### ISSUE THREAD

**Issue by mithrandi** [twisted/axiom#77]
Something like this:
```
@empowers(IFoo)
class MyPowerup(Item):
    …
```
which would be equivalent to:
```
@implementer(IFoo)
class MyPowerup(Item):
    powerupInterfaces = [IFoo]
```

The main motivation for this is that it makes no sense to have an interface in `powerupInterfaces` that you do not implement. Note that you can still implement interfaces that you don't power up for:
```
@implementer(INotPowerupInterface)
@empowers(IFoo)
class MyPowerup(Item):
    …
```
works fine.

**Comment by mithrandi** [comment]
Any thoughts on this?

**Comment by mithrandi** [comment]
Alternative naming suggestions wanted: `empowers` is the wrong tense, but `empowerer` is a bit awkward.

**Comment by ldanielburr** [comment]
I think "@bestows" might work.  You want to be able to say that this class provides the following powerup, but "provides" is already a term with a specific meaning in zope.interface.

Some other options:
"@bequeathes"
"@confers"
"@imparts"
"@awards"

**Comment by ldanielburr** [comment]
Looking at this ticket again, I think I'd call it @empowerment.  @empowerment(IFoo) reads sensibly, at least to me.
